# Generated by Django 6.0.4 on 2026-04-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['merchant', 'status'], name='payout_payo_merchan_e19692_idx'),
        ),
    ]
