# Generated by Django 6.0.4 on 2026-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0002_alter_payout_idempotency_key_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payout',
            name='payout_payo_merchan_e19692_idx',
        ),
        migrations.RemoveField(
            model_name='idempotency',
            name='created_at',
        ),
        migrations.AddField(
            model_name='payout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(max_length=100),
        ),
    ]
