# Generated by Django 6.0.4 on 2026-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0003_remove_payout_payout_payo_merchan_e19692_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='bank_account_id',
            field=models.CharField(default='default_account', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledger',
            name='type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('HELD', 'Held')], max_length=10),
        ),
    ]
